const fs=require('fs');const {chromium}=require('/Users/wutian/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const sharp=require('/Users/wutian/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Users/wutian/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/v2/');await page.waitForTimeout(600);await page.evaluate(()=>MillyRig.reset());const defs=await page.evaluate(()=>MillyRig.definitions.filter(d=>!['hairStiffness','hairDamping'].includes(d[0])));const results=[];
for(const d of defs){const key=d[0];await page.evaluate(([k,lo,tab])=>{MillyRig.reset();MillyRig.showView(tab==='body'?'full':'face');MillyRig.setOutfit(k.startsWith('skirt'));MillyRig.set({[k]:lo,...(k==='physics'?{wind:1}: {})})},[key,d[2],d[5]]);await page.waitForTimeout(key==='physics'?700:40);const a=await sharp(await page.locator('#stage').screenshot()).raw().toBuffer();await page.evaluate(([k,hi])=>MillyRig.set({[k]:hi}),[key,d[3]]);await page.waitForTimeout(key==='physics'||key==='wind'?900:40);const b=await sharp(await page.locator('#stage').screenshot()).raw().toBuffer();let changed=0,sum=0;for(let i=0;i<a.length;i++){const v=Math.abs(a[i]-b[i]);sum+=v;if(v>12)changed++}results.push({key,changedChannels:changed,meanAbsoluteChange:sum/a.length,pass:changed>5});console.log(key,changed>5?'OK':'NO VISUAL CHANGE',changed);}
// Real UI interaction and stable manual values.
await page.reload();await page.waitForTimeout(300);await page.locator('[data-tab="head"]').click();await page.locator('#range-headX').fill('22');await page.locator('#range-headX').dispatchEvent('input');await page.waitForTimeout(300);const ui=await page.evaluate(()=>({x:MillyRig.parameters.headX,mode:MillyRig.state.mode,playing:MillyRig.state.playing}));
await page.locator('[data-tab="body"]').click();await page.locator('#range-skirt1').fill('0.8');await page.locator('#range-skirt1').dispatchEvent('input');const skirtToggle=await page.evaluate(()=>MillyRig.state.showSkirt);
const dl=page.waitForEvent('download');await page.locator('#export').click();const download=await dl;await download.saveAs('rigging/milly/v2/evidence/roundtrip-pose.json');await page.locator('#reset').click();await page.locator('#import-file').setInputFiles('rigging/milly/v2/evidence/roundtrip-pose.json');await page.waitForTimeout(100);const imported=await page.evaluate(()=>({x:MillyRig.parameters.headX,skirt:MillyRig.parameters.skirt1}));
await page.locator('#reference-open').click();const video=await page.locator('#reference-video').evaluate(v=>({readyState:v.readyState,duration:v.duration}));await page.locator('#reference-close').click();
await page.locator('#timeline').fill('18');await page.locator('#timeline').dispatchEvent('input');const scrub=await page.evaluate(()=>MillyRig.state);
const ids=await page.evaluate(()=>{const a=[...document.querySelectorAll('#milly-svg [id]')].map(n=>n.id);return a.filter((v,i)=>a.indexOf(v)!==i)});
await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForTimeout(300);await page.screenshot({path:'rigging/milly/v2/evidence/mobile.png',fullPage:true});const mobile=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));
const filePage=await browser.newPage();await filePage.goto('file:///Users/wutian/Desktop/coding/AstraLayering/rigging/milly/v2/index.html');await filePage.waitForTimeout(200);const standalone=await filePage.evaluate(()=>!!window.MillyRig&&MillyRig.paths>0);
const report={parameters:results,ui,skirtToggle,imported,video,scrub,duplicateIds:ids,mobile,standalone,errors};fs.writeFileSync('rigging/milly/v2/evidence/validation.json',JSON.stringify(report,null,2));console.log('REPORT',report);await browser.close()})();
