const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium}=require('/Users/wutian/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='/Users/wutian/Desktop/coding/AstraLayering/rigging/milly',out=path.join(root,'v2/evidence/reference-review');const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const v={};for(const f of ['index.html','rig.js','motion-tracks.json','reference.mp4'])v[f]=sha(fs.readFileSync(path.join(root,f)));fs.writeFileSync(path.join(out,'v1-versions.json'),JSON.stringify(v,null,2));const html=fs.readFileSync(path.join(root,'index.html'));fs.writeFileSync(path.join(out,'reviewed-v1-index.html'),html);
const browser=await chromium.launch({headless:true,executablePath:'/Users/wutian/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'});const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.route('http://127.0.0.1:8765/',r=>r.fulfill({status:200,contentType:'text/html',body:html}));await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>window.MillyRig);
const data={poses:[],playback:[]};await page.evaluate(()=>{MillyRig.seek(0);document.getElementById('play').click();window.reviewRAF=[];window.reviewLast=performance.now();function observe(now){window.reviewRAF.push(now-window.reviewLast);window.reviewLast=now;requestAnimationFrame(observe)}requestAnimationFrame(observe)});let started=Date.now();for(let i=0;i<3;i++){await page.waitForTimeout(2500);data.playback.push({wallSeconds:(Date.now()-started)/1000,...await page.evaluate(()=>({animationTime:MillyRig.state.time,dtMean:reviewRAF.reduce((a,b)=>a+b,0)/reviewRAF.length,fpsUI:window.millyFPS}))});}
for(const t of [0,.5,1,3,4.5,6,8,9,12,15,18,24]){await page.evaluate(t=>{MillyRig.seek(t);MillyRig.showView('portrait')},t);await page.locator('#stage').screenshot({path:path.join(out,'v1-at-'+t+'.png')});data.poses.push({t,parameters:await page.evaluate(()=>MillyRig.parameters)});}
for(const [name,p]of [['armL-in',{armL:-30,elbowL:-30,bodyX:10}],['armR-in',{armR:-30,elbowR:-30,bodyX:-10}],['cross-both',{armL:-30,armR:-30,elbowL:30,elbowR:30}],['body-plus',{bodyX:10,bodyY:10,bodyZ:10}]]){await page.evaluate(p=>{MillyRig.reset();MillyRig.set({physics:0,...p});MillyRig.showView('full')},p);await page.locator('#stage').screenshot({path:path.join(out,'v1-'+name+'.png')});}
fs.writeFileSync(path.join(out,'v1-checks.json'),JSON.stringify(data,null,2));await browser.close();console.log(JSON.stringify({versions:v,playback:data.playback},null,2));})().catch(e=>{console.error(e);process.exit(1)});
