const fs=require('fs'),path=require('path'),{chromium}=require('/Users/wutian/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=__dirname,html=fs.readFileSync(path.join(out,'reviewed-index.html'),'utf8');
(async()=>{const browser=await chromium.launch({executablePath:'/Users/wutian/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.route('http://127.0.0.1:8765/v2/',r=>r.fulfill({status:200,contentType:'text/html',body:html}));await page.goto('http://127.0.0.1:8765/v2/');await page.waitForFunction(()=>window.MillyRig);
 const poses=[['threshold-before',{armL:7,armR:7,elbowL:15,elbowR:15}],['threshold-after',{armL:7.1,armR:7.1,elbowL:15,elbowR:15}],['neutral-turn-before',{bodyX:.99}],['neutral-turn-after',{bodyX:1.01}],['combo-shoulder',{headX:30,headY:30,headZ:30,bodyX:10,bodyY:10}],['arms-open',{armL:-15,armR:-15,elbowL:-15,elbowR:-15}],['arms-front-left',{armL:-30,elbowL:-30,bodyX:10}],['front-bend',{armL:-7,armR:-7,elbowL:30,elbowR:30}],['arms-back',{armL:30,armR:30,elbowL:30,elbowR:30}],['one-back',{armL:25,elbowL:30,armR:-10,elbowR:-10,bodyX:10}]];
 for(const a of[10,12,14,16,18,20,22,25])poses.push(['tuck-'+a,{armL:a,armR:a,elbowL:25,elbowR:25}]);
 for(const[name,p]of poses){await page.evaluate(({name,p})=>{MillyRig.reset();MillyRig.set({...p,physics:0});MillyRig.showView(name==='combo-shoulder'?'face':'portrait')},{name,p});await page.locator('#stage').screenshot({path:path.join(out,name+'.png')});}
 await page.evaluate(()=>{MillyRig.reset();MillyRig.set({armL:4,armR:4,elbowL:25,elbowR:25,physics:0});MillyRig.set({armL:25,armR:25},{smooth:true});MillyRig.showView('portrait')});
 const snapshots=await page.evaluate(()=>new Promise(resolve=>{let stamps=[0,50,100,150,200,300,450,700,1000],start=performance.now(),a=[];function tick(now){if(now-start>=stamps[0]){stamps.shift();a.push({time:now-start,p:MillyRig.renderedParameters,svg:document.querySelector('#milly-svg').outerHTML})}if(stamps.length)requestAnimationFrame(tick);else resolve(a)}requestAnimationFrame(tick)}));
 const render=await browser.newPage({viewport:{width:650,height:800}});for(let i=0;i<snapshots.length;i++){let f=snapshots[i];let svg=f.svg.replace(/style="[^"]*"/,'').replace('<svg ','<svg style="position:relative;display:block;width:650px;height:800px" ');await render.setContent('<body style="margin:0;background:#f6f2ec"><style>.skirt-part{display:none}.show-skirt .skirt-part{display:inline}</style>'+svg);await render.screenshot({path:path.join(out,`continuous-tuck-${i}.png`)});delete f.svg;}await render.close();
 await page.evaluate(()=>{MillyRig.reset();MillyRig.seek(0);document.querySelector('#play').click()});await page.waitForTimeout(2200);const perf=await page.evaluate(()=>({fps:window.millyFPS,state:MillyRig.state}));
 await page.setViewportSize({width:320,height:844});await page.evaluate(()=>{MillyRig.reset();document.querySelector('#follow').click()});await page.screenshot({path:path.join(out,'mobile-follow.png'),fullPage:true});const follow=await page.locator('#follow').evaluate(e=>({color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor}));fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({poses,snapshots,errors,perf,follow},null,2));await browser.close();console.log('done',perf,follow);})();
