const fs=require('fs'),path=require('path'),{chromium}=require('/Users/wutian/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const out=__dirname,html=fs.readFileSync(path.join(out,'reviewed-index.html'),'utf8');
(async()=>{const browser=await chromium.launch({executablePath:'/Users/wutian/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.route('http://127.0.0.1:8765/v3/',r=>r.fulfill({status:200,contentType:'text/html',body:html}));await page.goto('http://127.0.0.1:8765/v3/');await page.waitForFunction(()=>window.MillyRig);
const poses=[['body-neutral',{}],['body-turn-plus',{bodyX:10}],['body-turn-minus',{bodyX:-10}],['body-down',{bodyY:10}],['body-up',{bodyY:-10}],['body-combination',{bodyX:10,bodyY:10,bodyZ:10}],['body-arms-open',{armL:-30,armR:-30,elbowL:-30,elbowR:-30}],['body-arms-tuck',{armL:30,armR:30,elbowL:30,elbowR:30}],['body-mid-tuck',{armL:14,armR:14,elbowL:25,elbowR:25}],['body-asymmetric',{armL:25,elbowL:30,armR:-10,elbowR:-10,bodyX:10}],['face-neutral',{}],['face-left',{headX:-30}],['face-right',{headX:30}],['face-down',{headY:30}],['face-up',{headY:-30}],['face-closed-turn',{headX:30,headY:15,headZ:10,eyeLOpen:0,eyeROpen:0,mouthOpen:0}],['face-combination',{headX:30,headY:30,headZ:30,bodyX:10,bodyY:10}],['face-combination-minus',{headX:-30,headY:-30,headZ:-30,bodyX:-10,bodyY:-10}]];
for(const[name,p]of poses){await page.evaluate(({name,p})=>{MillyRig.reset();MillyRig.set({...p,physics:0});MillyRig.showView(name.startsWith('face')?'face':'portrait');if(name.startsWith('body'))document.querySelector('#milly-svg').setAttribute('viewBox','270 280 470 560')},{name,p});await page.locator('#stage').screenshot({path:path.join(out,name+'.png')});}
const sequences=[];
for(const[name,start,stamps]of[['turn',2.35,[2.6,2.8,3,3.2,3.5]],['return',4.35,[4.6,4.8,5,5.2,5.4,5.6]],['nod',14.8,[15.0,15.2,15.3,15.4,15.5,15.7,15.9]]]){await page.evaluate(s=>{MillyRig.reset();MillyRig.seek(s);MillyRig.showView('portrait');document.querySelector('#play').click()},start);const frames=await page.evaluate(targets=>new Promise(resolve=>{let out=[];function tick(){const time=MillyRig.state.time;if(time>=targets[0]){const target=targets.shift();out.push({target,time,p:MillyRig.renderedParameters,physics:MillyRig.physics,svg:document.querySelector('#milly-svg').outerHTML})}if(targets.length)requestAnimationFrame(tick);else resolve(out)}requestAnimationFrame(tick)}),stamps);sequences.push({name,frames});}
await page.evaluate(()=>{MillyRig.reset();MillyRig.set({headX:-25,headZ:-12,bodyX:-7,wind:0});MillyRig.showView('portrait');});await page.waitForTimeout(150);await page.evaluate(()=>MillyRig.set({headX:25,headZ:12,bodyX:7},{smooth:true}));
const smoothFrames=await page.evaluate(()=>new Promise(resolve=>{let stamps=[0,70,140,240,400,600,850,1100,1500,2200],start=performance.now(),a=[];function tick(now){if(now-start>=stamps[0]){stamps.shift();a.push({time:now-start,p:MillyRig.renderedParameters,physics:MillyRig.physics,svg:document.querySelector('#milly-svg').outerHTML})}if(stamps.length)requestAnimationFrame(tick);else resolve(a)}requestAnimationFrame(tick)}));sequences.push({name:'smooth',frames:smoothFrames});
const render=await browser.newPage({viewport:{width:650,height:800}});for(const s of sequences)for(let i=0;i<s.frames.length;i++){const f=s.frames[i];let svg=f.svg.replace(/style="[^"]*"/,'').replace('<svg ','<svg style="position:relative;display:block;width:650px;height:800px" ');await render.setContent('<body style="margin:0;background:#f6f2ec"><style>.skirt-part{display:none}.show-skirt .skirt-part{display:inline}</style>'+svg);await render.screenshot({path:path.join(out,`${s.name}-${i}.png`)});delete f.svg;}fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({poses,sequences,errors},null,2));await browser.close();console.log('done');})();
