const fs=require('fs'),path=require('path'),{chromium}=require('/Users/wutian/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),{PNG}=require('/Users/wutian/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/pngjs');
const out=__dirname,html=fs.readFileSync(path.join(out,'reviewed-index.html'),'utf8');
(async()=>{const browser=await chromium.launch({executablePath:'/Users/wutian/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.route('http://127.0.0.1:8765/v2/',r=>r.fulfill({status:200,contentType:'text/html',body:html}));await page.goto('http://127.0.0.1:8765/v2/');await page.waitForFunction(()=>window.MillyRig);
 const records={errors,pairs:[]};
 for(const a of[0,7,7.1,10,12,14,16,18,22,25,30]){await page.evaluate(a=>{MillyRig.reset();MillyRig.set({armL:a,armR:a,elbowL:25,elbowR:25,physics:0});MillyRig.showView('portrait')},a);await page.locator('#stage').screenshot({path:path.join(out,'tuck-'+a+'.png')});}
 for(const arm of[-30,-7,0])for(const bodyX of[-10,0,10]){
 let buffers=[];for(const elbow of[0,.01]){const name=`elbow-switch-a${arm}-b${bodyX}-e${elbow}`;await page.evaluate(p=>{MillyRig.reset();MillyRig.set({...p,physics:0});MillyRig.showView('full')},{armL:arm,armR:arm,elbowL:elbow,elbowR:elbow,bodyX});buffers.push(await page.locator('#stage').screenshot({path:path.join(out,name+'.png')}));}
 const [a,b]=buffers.map(x=>PNG.sync.read(x));let changed=0,max=0;for(let i=0;i<a.data.length;i+=4){const d=Math.max(...[0,1,2].map(j=>Math.abs(a.data[i+j]-b.data[i+j])));if(d>16)changed++;max=Math.max(max,d)}records.pairs.push({arm,bodyX,changed,max,pixels:a.width*a.height});}
 for(const [name,p]of [['front-bend',{armL:-7,armR:-7,elbowL:30,elbowR:30}],['one-back',{armL:25,elbowL:30,armR:-10,elbowR:-10,bodyX:10}],['front-open',{armL:-15,armR:-15,elbowL:-15,elbowR:-15}]]){await page.evaluate(p=>{MillyRig.reset();MillyRig.set({...p,physics:0});MillyRig.showView('portrait')},p);await page.locator('#stage').screenshot({path:path.join(out,name+'.png')});}
 await page.evaluate(()=>{MillyRig.reset();MillyRig.set({armL:-2,armR:-2,elbowL:25,elbowR:25,physics:0});MillyRig.set({armL:25,armR:25},{smooth:true});MillyRig.showView('portrait')});
 const snapshots=await page.evaluate(()=>new Promise(resolve=>{let stamps=[0,25,50,75,100,150,200,300,450,700],start=performance.now(),a=[];function tick(now){if(now-start>=stamps[0]){stamps.shift();a.push({time:now-start,p:MillyRig.renderedParameters,svg:document.querySelector('#milly-svg').outerHTML})}if(stamps.length)requestAnimationFrame(tick);else resolve(a)}requestAnimationFrame(tick)}));const render=await browser.newPage({viewport:{width:650,height:800}});for(let i=0;i<snapshots.length;i++){let f=snapshots[i];let svg=f.svg.replace(/style="[^"]*"/,'').replace('<svg ','<svg style="position:relative;display:block;width:650px;height:800px" ');await render.setContent('<body style="margin:0;background:#f6f2ec"><style>.skirt-part{display:none}.show-skirt .skirt-part{display:inline}</style>'+svg);await render.screenshot({path:path.join(out,`continuous-tuck-${i}.png`)});delete f.svg;}records.snapshots=snapshots;fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify(records,null,2));await browser.close();console.log('done',records.pairs);})();
